### ISSUE TITLE
Please submit a rockspec to MoonRocks

### ISSUE THREAD

**Issue by hishamhm** [britzl/luacov-cobertura#1]
I added links to luacov-cobertura and luacov-coveralls in the README.md file for LuaCov. I wanted to point users to install the via LuaRocks, but then I found that luacov-cobertura is missing at the MoonRocks repository. You can probably take a look at the luacov-coveralls rockspec for inspiration. Thanks!

**Comment by britzl** [comment]
Thanks! http://luarocks.org/modules/britzl/luacov-cobertura
