### ISSUE TITLE
Lua 5.4 support

### ISSUE THREAD

**Issue by andreyorst** [britzl/luacov-cobertura#7]
Just tried installing this with `luarocks` on my Fedora 34, which only has lua 5.4 in the repos, and got this error:

```
luarocks install --local --check-lua-versions luacov-cobertura
luacov-cobertura not found for Lua 5.4.
Checking if available for other Lua versions...
Checking for Lua 5.1...
Checking for Lua 5.2...
Checking for Lua 5.3...

Error: No results matching query were found for Lua 5.4.
luacov-cobertura supports only Lua 5.1 and Lua 5.2 and Lua 5.3 but not Lua 5.4.
```

**Comment by britzl** [comment]
I'm not very familiar with LuaRocks but the rockspec does specify Lua >= 5.1:

https://github.com/britzl/luacov-cobertura/blob/master/luacov-cobertura.rockspec#L12

Shouldn't this be enough?

**Comment by andreyorst** [comment]
huh, apparently Luarocks has different rockspec in the registry: https://luarocks.org/modules/ssharma/luacov-cobertura
Which leads to the fork of this project https://github.com/krux/luacov-cobertura, which in turn specifies `lua >= 5.1, < 5.4` dependency. Perhaps rockspec should be updated in the Luarocks registry?

**Comment by britzl** [comment]
Maybe. I haven't tested this Lua module in a long time. Perhaps it doesn't work with Lua 5.4?

**Comment by andreyorst** [comment]
I will check by manually building with the rockspec from this repo, but I suppose, that version `< 5.4` was added because in 2017 there was no 5.4 officially released. Similarly to how luacov specifies `< 5.5` as upper bound right now

**Comment by andreyorst** [comment]
@britzl no it seems to work just fine, although I had to alter the rockspec name to build this properly. I'm a bit confused with versioning though
